### ISSUE TITLE
Chrome Web Store requirements

### ISSUE THREAD

**Issue by surreal8** [art-institute-of-chicago/browser-extension#43] opened 2019-09-17 21:22 UTC
here’s what we need to publish to the store:
1. favicon/icon - 128x128
2. Summary sentence (we’ll grab from our github)
3. Screenshots (sizes mentioned below)
4. Tiles (sizes mentioned below)

Tile sizes:
Small tile - 440x280:
Large tile - 920x680: (optional)
Marquee - 1400x560: (optional)

Screenshot:
1280x800 or 640x400

**Comment by IllyaMoskvin** [comment] 2019-09-19 20:34
Dupe of #32. I'll move this information there.

**Closed by IllyaMoskvin** 2019-09-19 20:34 UTC
